export const sharedInitialBuildSystemRules = [
  "Never modify files under packages/kernel/**. The kernel is frozen platform code.",
  "Never rewrite or replace the platform shell, router, route registry, API server, contracts, workspace config, or build tooling.",
  "Only emit files that live inside approved generated web directories for the initial build surface.",
  "Every generated TSX page, layout, and component file must include a default export.",
  "Prefer semantic HTML and Tailwind utility classes. Do not require additional npm packages or remote assets.",
  "Only author generated app code with approved sandbox packages: react, react-dom, react-router-dom, lucide-react, framer-motion, clsx, and tailwind-merge, plus local relative imports and @/ aliases.",
  "Keep output deterministic, concise, and production-presentable rather than experimental.",
  "ALWAYS import icons from lucide-react. Never use SVG placeholders, grey circles, emoji, or inline SVGs as icons unless the user explicitly requested a custom icon or image.",
  "Never import from react-icons, @heroicons, or any other icon library besides lucide-react.",
  "EVERY input, textarea, and select must include a realistic placeholder attribute. Never leave a form field blank and never use placeholder='...'.",
  "Maintain readable contrast at all times. Never place white or light text on white or light backgrounds. Never place dark text on dark backgrounds. Inputs on light surfaces must use dark text such as text-gray-900, and text on colored buttons must be white or clearly contrasting.",
  "Seed lists, tables, feeds, and cards with 3 to 5 rows of realistic example data using real-looking names, dates, prices, counts, statuses, and labels. Never use Lorem ipsum, Sample text, Item 1, or other generic filler.",
  "All buttons must use explicit action labels such as Save Changes, Add Task, Send Message, View Invoice, or Start Free Trial.",
  "Never put the entire app in one component. Split the experience into logical subcomponents such as Sidebar, TopBar, PageContent, Card, Modal, FeedItem, ProductGrid, or FormStep.",
  "The generated app must include a stable scaffold: route manifest, theme/tokens file, navigation config, shared data file, AppShell layout component, and shared UI primitives before or alongside route files.",
  "The generated scaffold already provides @/lib/utils with a cn helper. Reuse it for className composition instead of reimplementing utility helpers.",
  "Route files should contain route-specific content only. Shared navigation, shell layout, responsive frame logic, and repeated UI primitives belong in the scaffold files, not duplicated inside each page.",
  "If you touch AppShell or a shared UI module, preserve its default export so route files can import it safely.",
  "Favor editing theme, navigation, AppShell, or shared UI modules for global changes instead of rewriting every route file.",
] as const;
